name: "Send Telegram Message"
description: "Send a message to a Telegram chat using a bot token."
author: "JobMetric"

inputs:
  bot_token:
    description: "Telegram bot token created via BotFather"
    required: true
  chat_id:
    description: "Target Telegram chat ID (user, group, or channel)"
    required: true
  message:
    description: "Message text that will be sent to Telegram"
    required: true
  parse_mode:
    description: "Telegram parse_mode (Markdown, HTML, MarkdownV2)"
    required: false
    default: "Markdown"

runs:
  using: "composite"
  steps:
    - name: Send Telegram message
      shell: bash
      run: |
        # Create a temporary file for the message to handle multiline content properly
        MESSAGE_FILE=$(mktemp)
        printf '%b' "${{ inputs.message }}" > "$MESSAGE_FILE"
        
        # Send message using curl with --data-urlencode from file
        # This ensures proper encoding of special characters and multiline content
        RESPONSE=$(curl -sS -w "\n%{http_code}" -X POST "https://api.telegram.org/bot${{ inputs.bot_token }}/sendMessage" \
          -d "chat_id=${{ inputs.chat_id }}" \
          --data-urlencode "text@$MESSAGE_FILE" \
          -d "parse_mode=${{ inputs.parse_mode }}" \
          -d "disable_web_page_preview=true")
        
        # Clean up temp file
        rm -f "$MESSAGE_FILE"
        
        # Parse response
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')
        
        if [ "$HTTP_CODE" = "200" ]; then
          echo "✅ Telegram message sent successfully"
          echo "Response: $BODY"
        else
          echo "❌ Failed to send Telegram message"
          echo "HTTP Code: $HTTP_CODE"
          echo "Response: $BODY"
          exit 1
        fi
